### ISSUE TITLE
DHT store

### ISSUE THREAD

**Issue by onkarshedge** [frostwire/frostwire-jlibtorrent#106]
We can store arbitrary data in the DHT as per the [specification](http://www.bittorrent.org/beps/bep_0044.html) both mutable and immutable.
Can we increase the size to more than 1000 bytes ?

**Comment by gubatron** [comment]
no you cannot increase the size to more than 1000 bytes. The DHT is not meant for storing data, it's meant to index data. If you want to store data I suggest you use torrents across your clients and use the DHT to point to those torrents.

You can't raise that limit to more than 1000 bytes because this is as much as you can fit per UDP package, the DHT transport layer is UDP.

Another solution would be to spread the data on multiple buckets, but you'd only be harming the DHT by doing this, and I don't think it'd be a good experience for the user to make so many requests to retrieve the data.

1000 bytes is a lot :)
