### ISSUE TITLE
Add https url seed, the alert hint 'unsupported URL protocol'

### ISSUE THREAD

**Issue by monkeycz** [frostwire/frostwire-jlibtorrent#113]
Why remove the '-DTORRENT_USE_OPENSSL' from run-swig.sh?

**Comment by aldenml** [comment]
Because we don't support torrents over ssl any more. Now, in the process of removing the dependency of `libssl` you loose the support for internal HTTPS request, but it seems like a reasonable compromise since web seeds don't need to use SSL. This results in a significant space save in the final binary, while still having `libcrypto` for fast hashing.

**Comment by monkeycz** [comment]
thx
