### ISSUE TITLE
1.2  HTTP HTTPS Config

### ISSUE THREAD

**Issue by xiongke15117937934** [frostwire/frostwire-jlibtorrent#121]
Why do I use Travis CI to run your project does not generate the jar file of the project, I am very curious, do not understand, hope to be able to explain, this code can make -DTORRENT_USE_OPENSSL=1 your project support Https? My boss told me I should do so, we would like to use the latest version of the code, to run our the project.

**Comment by aldenml** [comment]
The jars are generated locally with `gradle jars`. In order to get support for ssl put `on` on this line https://github.com/frostwire/frostwire-jlibtorrent/blob/master/swig/Jamfile#L27, but I repeat, I don't think you really need HTTPS web seeds if you don't use the feature of Torrents over SSL as in here http://blog.libtorrent.org/2012/01/bittorrent-over-ssl/

**Comment by xiongke15117937934** [comment]
Local production jar files, keep the production.so file?? So that it can be the latest edition to support HTTPS requests?

**Comment by xiongke15117937934** [comment]
The result + = < SSL > off; Change the result + = < SSL > on; In the local compile the generated JAR file will support HTTPS?
