### ISSUE TITLE
new TorrentInfo(File) creates a false creationDate

### ISSUE THREAD

**Issue by dessalines** [frostwire/frostwire-jlibtorrent#134]
I've noticed that when using `new TorrentInfo(File)`, it creates a bad creationDate, set to the current timestamp. I've notice that on a lot of torrents, creationDates are 0 (I think denoting optional). 

Using either `TorrentInfo.bdecode` or `Entry.bdecode` provide the right results.

**Comment by aldenml** [comment]
I will take a look at it

**Comment by aldenml** [comment]
What version of `jlibtorrent` are you using?

**Comment by dessalines** [comment]
`1.2.0.4` . It looks like creationDates are an optional field, and I've found that jlibtorrent will either set the creationDate to the current unix date, or to 0.

**Comment by aldenml** [comment]
I believe I found the reason for this inside `libtorrent`, the queue of PRs is no small, so it will take some time

**Comment by aldenml** [comment]
actually, looking at it again, everything seems to be correct, but I see that if the torrent is downloaded via magnet, it sets the time to the current date. Can you confirm that this is indeed your situation? If this is the case, I consider the behavior correct, since the torrent created with a magnet can't be expected to be equals to the original torrent.

**Comment by dessalines** [comment]
Yes I can, if its a magnet, it does set it to the current date.

**Comment by aldenml** [comment]
then, I will close the issue, because as I explained above, torrents fetched from the DHT are new torrents every time
