### ISSUE TITLE
fileProgress(TorrentHandle.FileProgressFlags.PIECE_GRANULARITY) return zero size array if we call it after force recheck.

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#148]
This behaviour occurs of torrent is not completely downloaded.
On seeding state it returns correct values.

**Comment by aldenml** [comment]
Yes, I see how that is possible, is a logic inside `libtorrent`, I will send a PR

**Comment by aldenml** [comment]
Fixed in `1.2.0.6-RC1`

**Comment by mianharisali** [comment]
@aldenml new it returns correct size array , but the file progress return 0. this happens only if we force recheck it.
even after force recheck it gives wrong values 0 for all files.

**Comment by aldenml** [comment]
`PIECE_GRANULARITY` only give you the pieces that have passed the hash check, since you are calling `forceRecheck` the internal progress cache is cleared, then this is the correct behavior. Now, this call to `forceRecheck` is asynchronous, so you need to work with the alerts to correctly time the call to `fileProgress`

**Comment by mianharisali** [comment]
@aldenml but even after force recheck the progress is 0 for all files.
