### ISSUE TITLE
Download Torrent on Android

### ISSUE THREAD

**Issue by narrow89** [frostwire/frostwire-jlibtorrent#17]
I'm trying to download a .torrent with frostwire-jlibtorrent library. I copy the sources directly in my project source folder like https://github.com/frostwire/frostwire-jlibtorrent says and I did a simple Activity to run it on a phone. I have no errors doing that but the download never starts. I used the example code from github frostwire and nothing.

I don't understand what I'm doing wrong. The source code is this:

    File torrentFile = new File("/sdcard/torr.torrent");
    
    System.out.println("Using libtorrent version: " + LibTorrent.version());
    
    final Session s = new Session();
    
    final TorrentHandle th = s.addTorrent(torrentFile, torrentFile.getParentFile());
    
    final CountDownLatch signal = new CountDownLatch(1);
    
    s.addListener(new TorrentAlertAdapter(th) {
        @Override
        public void onBlockFinished(BlockFinishedAlert alert) {
            int p = (int) (th.getStatus().getProgress() * 100);
            System.out.println("Progress: " + p);
        }
    
        @Override
        public void onTorrentFinished(TorrentFinishedAlert alert) {
            System.out.print("Torrent finished");
            signal.countDown();
        }
    });
    
    th.resume();
    
    signal.await();

I can see the torrent data, like name or the files inside it but I can't download it.

Please help I really need it :/

**Comment by gubatron** [comment]
Hi @narrow89 hopefully we'll be able to assist you.

I have to ask one stupid question to get started:

1. Are you sure the .torrent has online seeds and that the trackers it has are up?

Suggestions to find out what's going on:
2. Try overriding more methods on your `TorrentAlertAdapter`, like  
`public void stats(StatsAlert alert)`,`public void sessionStats(SessionStatsAlert alert)`, `public void torrentAdded(TorrentAddedAlert alert)`, `public void fileError(FileErrorAlert alert)`, `public void trackerError(TrackerErrorAlert alert)`, and others so you can print some information about the torrent status, I'm sure this will give you that "a-ha!" moment you're looking for and you will be able to solve the issue.

Since you're not getting any error messages

**Comment by aldenml** [comment]
You need to show us some of log(cat)

**Comment by narrow89** [comment]
Hai there, I just tried with a popular new torrent file and I just had a a-ha! moment hahaha.. Thank you so much!!
