### ISSUE TITLE
Private torrents doesn't work

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#170]
Hello. I noticed that I can't download private torrents: trackers doesn't work. I also checked this option in **frostwire** app and I could not download this torrent.

Screenshot with broken tracker:
http://imgur.com/GnGaiu7

Torrent file: [[CzT]Ubuntu_Budgie_v16_10_x64_.zip](https://github.com/frostwire/frostwire-jlibtorrent/files/1067612/CzT.Ubuntu_Budgie_v16_10_x64_.zip)

**P.S:** It works great in **qbittorrent**.

**Comment by aldenml** [comment]
Let me take a look at it (we are using `master` and I think qBittorrent is still in `1.0.1`)

**Comment by aldenml** [comment]
We don't support `HTTPS` trackers, we exclude any ssl support from `jlibtorrent` to save some space in the final binary (but still we use `libcrypto` for hash acceleration). Adding support in a custom build should be relatively easy, but not sure if worth the trouble, because HTTPS trackers does not provide any meaningful security.

I will close the issue, but feel free to provide arguments if you think this feature is necessary.

**Comment by J-qak** [comment]
[Here](http://blog.libtorrent.org/2012/01/bittorrent-over-ssl/) are in my opinion good reasons for actually implementing HTTPS tracker support, if I understand correctly. Being not implemented in `jlibtorrent` doesn't change the fact that some private trackers are already using HTTPS, so apps using `jlibtorrent` won't let users use these trackers.
If I have time, I'll try to experiment with it.

**Comment by aldenml** [comment]
After discussing the issue internally, we decided to revisit it

**Comment by aldenml** [comment]
Hi @J-qak, `1.2.0.13-RC5` is already out in maven, can you test it with your HTTPS trackers?

**Comment by proninyaroslav** [comment]
@aldenml It works perfectly.

**Comment by aldenml** [comment]
good to know, I'm in the process of making public the remaining support for torrents over SSL
