### ISSUE TITLE
Question about build procedures

### ISSUE THREAD

**Issue by elgatito** [frostwire/frostwire-jlibtorrent#217]
Hello.

As you are heavily targeting android platform, maybe you could share some experience in building libtorrent for android usage.

My question is, whether you have met segfaults, raised by libtorrent, which was caused not by code error, but caused by a build process? Some flags missed during libtorrent compilation/linkage, or some wrong version, or openssl was causing something like that?

I'm not sure how to properly investigate those issues on android (especially when I don't have own android device and have to ask users for some manipulations).

**Comment by gubatron** [comment]
in our experience most segfaults have been due to issues related to references to native objects lost from java land when the garbage collector comes in, we've been careful to avoid these issues and try to make jlibtorrent objects not so long lived.

as everything you need to do a little detective work to make sure your segfault is indeed due to a compilation issue, but most likely these occur due to null pointer exceptions, or trying to read into forbidden memory sections due to bad pointer references into the native side, or errors in libtorrent itself.

perhaps you have a stacktrace to share, very hard to tell. afaik our build scripts are working
