### ISSUE TITLE
build.gradle is using unset ossrhUsername and ossrhPassword properties

### ISSUE THREAD

**Issue by okimuri** [frostwire/frostwire-jlibtorrent#66]
There is a problem on lines #137 and #141 in build.gradle file; unset properties are used for authentication that lead to error when executing the Gradle build. 

Suggest the following fix (for both lines):

`authentication(
userName: hasProperty('ossrhUsername')?ossrhUsername:'', 
password: hasProperty('ossrhPassword')?ossrhPassword:''
)`

===
problem reproduced with

Gradle: 2.10
Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.11.2 x86_64

**Comment by aldenml** [comment]
Hi @okimuri, thank you for taking a look at it. Since we (the admins) are the only ones with credentials to upload to sonatype, I made it that `gradle build` does not sign the jars. See https://github.com/frostwire/frostwire-jlibtorrent/blob/master/build.gradle#L103

The libraries should be in `./build/libs/`. Let me know if this works for you.
