### ISSUE TITLE
OpenSSL in the Play Store

### ISSUE THREAD

**Issue by se-bastiaan** [frostwire/frostwire-jlibtorrent#83]
Today Google sent out [an important email](https://gist.github.com/se-bastiaan/0f7daf07b5401f2d6dc1b541038b4e46) regarding OpenSSL being used in applications.

Someone brought this to [my attention](https://github.com/se-bastiaan/TorrentStream-Android/issues/3) regarding a library of mine that is relying on jlibtorrent and I thought it might be good to relay the message, since LibTorrent is the part of the equation that uses OpenSSL.

Google's deadline is set in July which means that there is still some time left. But I think it would be better to fix this as soon as possible (security etc important etc :smile:)

I do not know if this should be fixed by recompiling the binaries for jlibtorrent or by changing some code in the LibTorrent project, but this seemed the most appropriate place to post the issue.

**Comment by gubatron** [comment]
If I remember correctly we're up to date with the openssl version we link against.
Even in my system (I'm not the one that builds) I already have `1.0.2g` (updated March 25th)

**Comment by aldenml** [comment]
@se-bastiaan I will take care of it

**Comment by diaconuliviu85** [comment]
I have the same problem myself, and if I unzip the app is the 2015 version of OpenSSL.
although computer I installed version dein March 16th (1.1). The library has separate version 1.0.1d.
Thank you

**Comment by gubatron** [comment]
Thanks @aldenml we're all in this together as this library is used on our Google Play app as well.

**Comment by aldenml** [comment]
@se-bastiaan @diaconuliviu85 version 1.1.0.23 is published in master. It has openssl 1.0.2g.

If you find API braking changes, just remove the bunch of "get" prefix from the methods. Also, I don't know if you are aware that the android Intel x86 and x86_64 versions suffer from the issue of "text relocations"  in Android 6.0 AND you target API 23. This is probable due to some assembler used in OpenSSL that I still need to figure out where it is.

Added this method for convenience: https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/LibTorrent.java#L63

Testing is welcome, thanks for reporting this

**Comment by gubatron** [comment]
That was fast, thanks!
![chris-farley-you-are-awesome](https://cloud.githubusercontent.com/assets/163977/14258644/7fd56ff8-fa60-11e5-8dab-7aa9051e617f.jpg)

**Comment by diaconuliviu85** [comment]
Thanks .

**Comment by aldenml** [comment]
@se-bastiaan @diaconuliviu85 I recommend you take a look at https://github.com/frostwire/frostwire-jlibtorrent/issues/85#issuecomment-208448627

**Comment by diaconuliviu85** [comment]
Thanks .
