### ISSUE TITLE
Problems with Magnet download

### ISSUE THREAD

**Issue by WhiteTrashLord** [frostwire/frostwire-jlibtorrent#93]
Whenever I use your new code for the Magnet download, no more Magnet download is possible after some time. Please use a collection which is threadsafe for the LruCache. Currently it's a LinkedHashMap. This might solve my problem. Did you test if you can add hundreds of Magnets URIs within the same session and started by different threads?
And I think with your current code it's impossible to have more than 50 completed Magnet downloads within 1 seconds. This is probably not a problem for me, but you should make it possible to increase the cache via config.

**Comment by gubatron** [comment]
you know what, now that I look around, I don't ever see that Session.MAGNET_CACHE object ever being cleared, nor I see in its implementation any logic that extends `put` to call for the removal of the eldest element if the cache is full.

Not sure if extending a threadsafe collection might help, it just seems to me that we never finished implementing actual LRU caching logic in that class.

am I mistaken @aldenml ?

**Comment by WhiteTrashLord** [comment]
I tested the LruCache. I think it should delete old entries. removeEldestEntry is called by LinkedHashMap as far as I know. But there must be problem somwhere.

**Comment by aldenml** [comment]
@gubatron `LruCache` overrides `removeEldestEntry`.

@WhiteTrashLord could you provide more specifics about your current logic? When you say that no magnet downloads are possible, does it mean some sort of freeze or that it always timeout? Keep in mind that the way it's coded, under certain usage pattern, you can get to the situation that your magnets are constantly evicted resulting in a timeout of every `fetchMagnet` call.

We didn't test with hundreds of magnets because that's out of the scope for jlibtorrent (this actually hurts the network in the current form). There is no thread-safe guarantee for any `Session` method, so you should not use them in a multithread environment, and since this is "slow execution" method (you can't finish within 1 second per design), you better handle all the requests in a queue with some sort of batch logic.

I would like to have a better design overall, but this is part of the evolution of `libtorrent` understanding. The branch `libtorrent-RC_1_1` is in maintenance mode, only tracking new fixes in the native code, but we are more than happy to receive help.

**Comment by WhiteTrashLord** [comment]
Why do you use a synchronized (MAGNET_LOCK) then? I think in the past you wanted to support Magnet downloads for multiple threads. You did it only halfway?

**Comment by gubatron** [comment]
@aldenml interesting, so just overriding that method makes a LinkedList behave like an LRU cache.

**Comment by gubatron** [comment]
@WhiteTrashLord by the use of it, it looks like that lock is unrelated to that MAGNET_CACHE object.

**Comment by aldenml** [comment]
Yes, the lock is there because we (in frostwire) batch a few fetchs that run in a limited thread pool. We want to protect from a possible concurrent query to the native session. And yes, I want to support that and I didn't finish it with `1.1.X`, maybe for `1.2.X`.

**Comment by WhiteTrashLord** [comment]
Actually this doesn't make it a real LRU cache.

I thought more about the caching. Now I think that it's a bad idea to cache up to 50 torrents.
Some torrents can be very big. Like around 1 MB. So in a worst case scenario libtorrent would need around 50 MB RAM for the caching all the time. Please replace the 50 items LRUCache with a ConcurrentHashMap where you directly remove the item once it's used. You can make an option to enable the caching.

**Comment by gubatron** [comment]
@aldenml would this be one of those cases where some form "dependency injection" would be wanted, so if you want some different type of caching strategy you plug-it in there with your own implementation, otherwise use the default. is that what they call "dependency injection"?

**Comment by aldenml** [comment]
@gubatron no, and I believe what you are saying is basic OOP :)

@WhiteTrashLord I'm aware of the memory issue (and some torrents can be a lot more bigger) and I do want to keep them in memory. I can't see how `ConcurrentHashMap` can improve the situation. In any case, my idea is to put the current implementation in the trash and rethink the whole thing, since there are a lot more problems relate to the use of `libtorrent` to download magnets.

**Comment by gubatron** [comment]
a memory mapped torrent cache maybe?

**Comment by WhiteTrashLord** [comment]
When I use my own code for downloading magnets I have no problems. It's very similar to your code but it doesn't use your LRUCache. It would be more developer friendly if you can give us the option to disable this LRUCache. I don't want to use a fork of your code.

**Comment by gubatron** [comment]
@aldenml do you think it makes sense for now to provide a 

`session.enableMagnetCache(boolean enabled)`

method?

**Comment by aldenml** [comment]
The cache is necessary to avoid registering another callback/listener. I don't like the idea of patching something that is fundamentally broken to start with. @WhiteTrashLord you don't need to fork, just copy paste the relevant code to your own utility class and avoid using our `fetchMagnet`. We provide `swig()` methods in all wrapper classes to allow for any low level workaround. Even `Session` is bad designed btw.

**Comment by aldenml** [comment]
I'm closing this because there is no more LruCache in master, and `libtorrent-RC_1_1` is only in tracking mode, I think the solution with the new `TorrentManager` is a lot better now.
