### ISSUE TITLE
Creating trackerless torrent

### ISSUE THREAD

**Issue by onkarshedge** [frostwire/frostwire-jlibtorrent#97]
I want to create a trackerless torrent which uses DHT. I wrote the code to create a single file torrent and magnet link. Then to test my code I opened the magnet link in my qbittorrent client. It works fine sometimes and sometimes it gets stuck at downloading metadata. Same happened when I share the magnet link with my friends.
I also added various router bootstrap nodes. I read the specifications .torrent file can also contain nodes:[ip:port] entry, so should I add my own DHT node ? If yes how ?
Here is the link to my sample [code](https://gist.github.com/onkarshedge/81a412b985ad13c9180c5e474b128687)
I posted this here as there is no mailing list.

**Comment by gubatron** [comment]
So it's normal that sometimes you won't be able to fetch the magnet, a lot of it depends on the network configuration of you and your friends.

The most common reason for getting stuck there is double NAT issues.
If both of you are behind NATs, and you're the only ones announcing the torrent on the DHT, it will take a miracle to get the data to go through as you will both be announced publicly with internal IP:PORTs that are unreachable from outside of your local networks.

The current version of jlibtorrent actually improved upon finding out which ports are open to the outside to announce and our seeding rates have improved very much, still it doesn't work in 100% of the cases due to these double NAT issues.

If you keep having issues like that, you should probably check your internet router configuration and make sure the computer from where you're creating the DHT-tracked torrents is the DMZ, so that you have no issues port forwarding.

One way of knowing if jlibtorrent is not having issues is looking at what's coming on the `PORTMAP` alert. If you get portmap alerts with no errors, you will see on what ports you might be really waiting for messages.

Things get better as more peers try to fetch the same magnet link. As soon as there's one guy on the swarm who can accept connections, he will immediatly become the peer that will start spreading that magnet to more and more peers, some of which will be reachable.

>I also added various router bootstrap nodes. I read the specifications .torrent file can also contain nodes:[ip:port] entry, so should I add my own DHT node

I think you're talking about this:
```
ss.addDHTRouter(new Pair<String, Integer>("router.utorrent.com", 6881));
ss.addDHTRouter(new Pair<String, Integer>("router.bittorrent.com", 6881));
ss.addDHTRouter(new Pair<String, Integer>("dht.transmissionbt.com", 6881));
ss.addDHTRouter(new Pair<String, Integer>("router.bitcomet.com", 6881));
ss.addDHTRouter(new Pair<String, Integer>("dht.aelitis.com", 6881));
```

and how do you go about adding your own dht-bootstrapping server.

[You will need to build and run this bootstrap-dht server](https://github.com/bittorrent/bootstrap-dht). I tried building this source code about 2 months ago, and I think the build was broken, so you might have so spend some time to get it to build, I'm sure they'll welcome any pull requests you may have to bring the build scripts up to date.

Other than that, I saw that you already call `forceDHTAnnounce`. When you create the torrent you don't really want to add the IP:PORT of your jlibtorrent client, as the PORT won't be the same next time you run it. jlibtorrent will announce you on the DHT when the torrent starts, and it will keep re-announcing itself periodically all by itself.

Sorry for the lack of mailing list, but this works wonders.

**Comment by gubatron** [comment]
oh, and if you get a `PORTMAP_ERROR`, you're most def. firewalled/NATed and will have issues.

**Comment by gubatron** [comment]
TIP: If you want your alert handling to be more efficient, you can filter-in the alerts you care about here on your alert listener, just put the `ALERT_TYPE.swig()`, values on the returned `int[]` of the `types()` method:
```
      public int[] types() {
        return null;
      }
```

**Comment by gubatron** [comment]
Take a look at `BTEngine.java` on the FrostWire source code and you'll learn a lot.

**Comment by WhiteTrashLord** [comment]
Please tell me in which version the open port detection was improved. Was it made in 1.1.0.35 or earlier?

**Comment by gubatron** [comment]
`1.1.0.31`

**Comment by onkarshedge** [comment]
@gubatron Thank you so much.

**Comment by onkarshedge** [comment]
I had a look at the `BTEngine.java` .  I have some questions. The torrents from previous session are  added to current session by fast resume data. [Link to code](https://github.com/frostwire/frostwire/blob/0f81fac6fc32db6bfdc69c1ac07044d8a19cccda/common/src/main/java/com/frostwire/bittorrent/BTEngine.java#L1015) but `asyncAddTorrent` method from Session.java which calls [addTorrentSupport](https://github.com/frostwire/frostwire-jlibtorrent/blob/4b9dab6a3e86e230d97b99a61b6a24667f74cc00/src/main/java/com/frostwire/jlibtorrent/Session.java#L777) the resume data is not actually added, the line is commented.

Is that why you  rewrote the `addTorrentSupport` method in `BTEngine.java` with the line uncommented. [code](https://github.com/frostwire/frostwire/blob/0f81fac6fc32db6bfdc69c1ac07044d8a19cccda/common/src/main/java/com/frostwire/bittorrent/BTEngine.java#L860) and commented this [line](https://github.com/frostwire/frostwire/blob/0f81fac6fc32db6bfdc69c1ac07044d8a19cccda/common/src/main/java/com/frostwire/bittorrent/BTEngine.java#L820)

**Comment by gubatron** [comment]
can't remember exactly, but I bet this was code that we had on a branch, or that was private inside jlibtorrent and we sometimes just grab code and override it with modifications for own purposes.

gotta ask @aldenml he has a much better memory than me. Perhaps if you look at the "blame" where that function was added to BTEngine maybe there's a comment there.

That line was commented out on this commit where he was cleaning
https://github.com/frostwire/frostwire-jlibtorrent/commit/7bdc2338d10f0c4a24ed338fe53dddb3eb11ba47

(perhaps it needs to be added back)

**Comment by gubatron** [comment]
and then, when I commented that line, it seems it was because I was refactoring to work with magnets
https://github.com/frostwire/frostwire/commit/6ac2bed8bf41475f83f939d6560778dccf5e48e8

**Comment by onkarshedge** [comment]
@gubatron sorry to disturb you again.
But I am stuck at one part and not able to find solution. I want to seed a file.

I created a torrent of a file(bank.csv) and while adding torrent I added with different output directory. When the file is not present in the new directory, the state of torrent is Downloading, Correct.

`session.addTorrent(torrentFile, outputDir)`

and when, before running my code I copied the source file(bank.csv) to the output directory
the torrent state is stuck at CHECKING_FILES. The file is not altered only access time is changed.(This should not affect the checking...I guess).

And making auto_managed to True. The state changed from
CHECKING_FILES ->DOWNLOADING
DOWNLOADING -> SEEDING

```
case TORRENT_ADDED:
          TorrentAlert<?> torrentAlert = (TorrentAlert<?>) alert;
          log.info("torrent added alerttt  " + torrentAlert.torrentName());
          torrentAlert.handle().setAutoManaged(true);
```
How can I move it from CHECKING to SEEDING with auto_managed set to false.

**Comment by onkarshedge** [comment]
This did the trick.

```AddTorrentParams params = new AddTorrentParams();
      params.swig().set_ti(ti.swig());
      long flags = params.flags();
      flags &= add_torrent_params.flags_t.flag_seed_mode.swigValue();
      params.flags(flags);
```

**Comment by aldenml** [comment]
Hi @onkarshedge, good to know you solved the problem with the flag. The code line is commented in master(not usable at this moment) because that method will be removed form `Session` anyway. It's fine in `libtorrent-RC_1_1`.  I will notify here when the new stable version is out. Do you think it's ok to close this issue?

**Comment by aldenml** [comment]
1.1.0.36 is out in maven
